<a href="https://colab.research.google.com/github/pattichis/AIML/blob/main/Copy_of_Session_X_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Goals

1. Introduce Python lists and their operations.
2. Lists indexing and lists of lists.
3. Operations on NumPy arrays.

# NumPy arrays

## Create arrays using np.array()

NumPy array allow us to use fast arithmetic for list of lists or 2D matrices.

This is a new type of variable. Note that type refers to the kind of data that we can store.

We require an equal number of elements in each component list.

Assignment:
1. Note that np.array() is just used for converting to a new type.
2. What do you understand by a new type?  
3. Study the code and comment on why the last example fails.

In [ ]:
import numpy as np # import all the functions from numpy library. Use np for its functions.

str = "A string example"
print("str has type = ", type(str)) # type is used to return the kind of data.

num = 5.12
print("num has type = ", type(num))  # type returns the kind of data.

a = [[1, 2, 3], [4, 5, 6]] # regular list.
print(type(a))             # print the type of variable that a "is"

a_np = np.array(a)         # create numpy array.
print(a_np, type(a_np))    # We have a new type.

b = [[1, 2, 3], [4, 5]]    # b has lists of different sizes.
b_np = np.array(b)         # Conversion is not possible!
print(b_np)


str has type =  <class 'str'>
num has type =  <class 'float'>
<class 'list'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

1. Study the code.
2. Explain the values for len(b) and b.shape.

In [ ]:
import numpy as np

# Create a list:
a = [[1, 2, 3], [4, 5, 6]]

# Create a 2D NumPy array
b = np.array(a)

print("a = ", a, ", len(a) = ", len(a), ", type(a) = ", type(a))
print("b = ", b)
print("len(b) = ", len(b), ", b.shape = ", b.shape, ", type(b) = ", type(b))
print(" ")

a =  [[1, 2, 3], [4, 5, 6]] , len(a) =  2 type(a) =  <class 'list'>
b =  [[1 2 3]
 [4 5 6]]
len(b) =  2 , b.shape =  (2, 3) type(b) =  <class 'numpy.ndarray'>
 


## 1D matrix array creation using *

1. Study the code.
2. Create a 5 element row with the element of 6.

In [ ]:
print("List comprehension for a row")
c = np.array([3*[1]])
print("c = ", c)
print("len(c) = ", len(c), ", b.shape = ", c.shape)
print(" ")


## 2D matrix array creation using a list comprehension

1. Study the code below.
2. Explain the value of len(d).
3. Explain the value of d.shape.
4. Modify the example to make the shape (3, 5) of 2.

In [ ]:
d = np.array([3*[1] for row in range(4)])
print("d = ", d)
print("len(d) = ", len(d), ", d.shape = ", d.shape)
print(" ")

d =  [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
len(d) =  4 , d.shape =  (4, 3)
 


## Accessing NumPy Array elements

1. Study the code carefully.
2. Explain how b[0][0:2] prints what you get.


In [ ]:
# Create a list:
a = [[1, 2, 3], [4, 5, 6]]

# Create a 2D NumPy array
b = np.array(a)
print("b=", b)
print(" ")

print("Like lists: Access row by row.")
print("b[0] = ", b[0])
print("b[1] = ", b[1])
print(" ")

print("Like lists: Access elements using 2d indices")
print("b[0][0] = ", b[0][0])
print("b[1][2] = ", b[1][2])
print(" ")

print("Like lists: Access using 1D strides")
print("b[0][1:3] = ", b[0][1:3])
print("b[1][0:2] = ", b[1][0:2])
print("b[1][0:3:2] = ", b[1][0:3:2])
print(" ")

b= [[1 2 3]
 [4 5 6]]
 
Like lists: Access row by row.
b[0] =  [1 2 3]
b[1] =  [4 5 6]
 
Like lists: Access elements using 2d indices
b[0][0] =  1
b[1][2] =  6
 
Like lists: Access using strides
b[0][1:3] =  [2 3]
b[1][0:2] =  [4 5]
b[1][0:3:2] =  [4 6]
 


## Accessing 2D blocks

1. Study the code below.
2. Changing the single element 10 to 3.
3. Change the top row to all 1. Verify your answer.
4. Change the first column to 10. Verify your answer.
5. Change the lower-right elements to 5, 6. Verify your answer.

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("1. a = ", a)

print("2. a[0, 0] = ", a[0,0])
print("3. a[1, 0] = ", a[1,0])

a[1, 0] = 10
print("4. a[1, 0] = ", a[1,0])

a[0:2, 3:] = 5
print("5. a = ", a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
a[]= 1
a[]= 6
a =  [[ 1  2  3 -1 -1]
 [ 6  7  8 -1 -1]]


## Note "=" in Python does not copy NumPy array elements.

1. Study what happens after a[0]=100.
2. Explain what is unexpected here and why.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = a
print("a = ", a)
print("b = ", b)
print(" ")

a[0] = 100
print("a = ", a)
print("b = ", b)

a =  [1 2 3 4 5]
b =  [1 2 3 4 5]
 
a =  [100   2   3   4   5]
b =  [100   2   3   4   5]


## Copying NumPy arrays

1. What line did we change here?
2. How is the output different?

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = a.copy()
print("a = ", a)
print("b = ", b)
print(" ")

a[0] = 100
print("a = ", a)
print("b = ", b)

a =  [1 2 3 4 5]
b =  [1 2 3 4 5]
 
a =  [100   2   3   4   5]
b =  [1 2 3 4 5]


## Flattening arrays to one dimension

1. Study the code and discuss.
2. How is the size of b related to a?
3. How is b related to a?
4. Modify a to [[1, 2], [3, 4], [5, 6], [7, 8]]. What happens to b? Why?

In [ ]:
import numpy as np

a = np.array([[1, 2], [1, 2], [4, 5]]) # create an array.
b = a.flatten() # flatten all dimensions.

print("a = ", a, ", a.shape = ", a.shape)
print("b = ", b, ", b.shape = ", b.shape)


a =  [[1 2]
 [1 2]
 [4 5]] , a.shape =  (3, 2)
b =  [1 2 1 2 4 5] , b.shape =  (6,)


## Reshaping array rows into 2D matrices (e.g., images)

1. Study the code carefully.
2. Can you reshape each element to a size of 4x1. Why?
3. Can you reshape each element to a size of 3x2. Why or why not? Explain.

In [ ]:
# Original matrix has a square number of elements in each row.
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("a = ", a, ", a.shape = ", a.shape)
print(" ")

# Reshape each row:
for element in a:
  b = element.reshape(2, 2) # Reshape into 2 by 2.
  print("b = ", b, ", b.shape = ", b.shape)


a =  [[1 2 3 4]
 [5 6 7 8]] , a.shape =  (2, 4)
 
b =  [[1 2]
 [3 4]] , b.shape =  (2, 2)
b =  [[5 6]
 [7 8]] , b.shape =  (2, 2)


## A video as list of numpy frames.

1. Study the example carefully.
2. Add frame5 with some values. Verify your answer.
3. Comment out frame1 and frame2. Does it work? Explain.

In [ ]:
# Individual frames
frame1 = np.array([1, 2])
frame2 = np.array([3, 4])
frame3 = np.array([5, 6])
frame4 = np.array([7, 8])

video = [frame1, frame2, frame3, frame4]
print("video = ", video, ", type(video) = ")
print(" ")

for frame in video:
  print("frame = ", frame)

video =  [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])] , type(video) =  <class 'list'>
 
frame =  [1 2]
frame =  [3 4]
frame =  [5 6]
frame =  [7 8]
