<a href="https://colab.research.google.com/github/pattichis/AIML/blob/main/Session_X_1_Lists_and_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Goals

1. Introduce Python lists and their operations.
2. Lists indexing and lists of lists.
3. Operations on NumPy arrays.

# Working with Python Lists

## Create a list of numbers

1. Study the code below.
2. Create a list that contains 5.
3. Create [2, 2, 2] two different ways.
4. Create [1, 2, 3, 4] in variable e.

In [ ]:
# Empty list
a = []
print("a = ", a)

# One element
b = [1]
print("b = ", b)

# Standard list
c = [1, 2, 3]
print("c = ", c)

# Use * to duplicate elements
num_of_elements = 5
d = b*num_of_elements
print("d = ", d)

a =  []
b =  [1]
c =  [1, 2, 3]
d =  [1, 1, 1, 1, 1]


## Create a list using list comprehensions

1. Study the code below and answer the questions.
2. What do you think range(5) does?
3. What does append do?
4. Note the special format string for print. What does {i} mean?
5. Explain how you think the list comprehension works.

In [ ]:
# Add elements using a for loop
a = []

print("Entering the loop: a = ", a)
for i in range(5): # range generates values ...
  a.append(i)      # Expand the list ...
  print(f"a.append({i}) gives a = {a}") # Variable inside {} makes it print.
print("Exiting the loop: a = ", a)

# Add elements using list comprehension
a = [i for i in range(5)]
print("a = ", a)

Entering the loop: a =  []
a.append(0) gives a = [0]
a.append(1) gives a = [0, 1]
a.append(2) gives a = [0, 1, 2]
a.append(3) gives a = [0, 1, 2, 3]
a.append(4) gives a = [0, 1, 2, 3, 4]
Exiting the loop: a =  [0, 1, 2, 3, 4]
a =  [0, 1, 2, 3, 4]


## Indexing elements in a list

1. Study the examples below and discuss within your group.
2. Is a[5] valid? Explain.
3. What is the largest positive index? Explain.
4. What is the most negative index? Explain.


In [ ]:
a = [1, 2, 3, 4, 5]

print("a = ", a)
print("len(a) = ", len(a))
print(" ")

print("a[0] = ", a[0])
print("a[1] = ", a[1])
print("a[2] = ", a[2])
print(" ")

print("a[-1] = ", a[-1])
print("a[-2] = ", a[-2])
print("a[-3] = ", a[-3])


a =  [1, 2, 3, 4, 5]
len(a) =  5
 
a[0] =  1
a[1] =  2
a[2] =  3
 
a[-1] =  5
a[-2] =  4
a[-3] =  3


## Understanding what "=" means for lists

1. Run and study the code below.
2. Do you see anything strange? Explain.
3. What does "=" do here?


In [ ]:
a = [1, 2, 3, 4, 5]
b = a
print("a = ", a)
print("b = ", b)
print(" ")

a[0] = 100
print("a = ", a)
print("b = ", b)

a =  [1, 2, 3, 4, 5]
b =  [1, 2, 3, 4, 5]
 
a =  [100, 2, 3, 4, 5]
b =  [100, 2, 3, 4, 5]


## Optional: Reference counting

1. Examine how the number of references changes.
2. Click on <tt>{} Variables</tt> below. Do <tt>a</tt> and <tt>b</tt> exist? Explain.
3. What do you think <tt>del</tt> does?
4. Why do you think the number of references changes in each step?

In [ ]:
import sys
a = [1, 2, 3, 4, 5]
print("1. References to a: ", sys.getrefcount(a))

b = a
print("2. References to a: ", sys.getrefcount(a))

a[0] = 100
print("3. References to a: ", sys.getrefcount(a))
print("4. References to b: ", sys.getrefcount(b))

del a
print("5. References to b: ", sys.getrefcount(b))

del b


1. References to a:  2
2. References to a:  3
3. References to a:  3
4. References to b:  3
5. References to b:  2


## Copying lists

1. Study the example carefully.
2. What changed?
3. What do you think <tt>copy.deepcopy()</tt> does?

In [ ]:
import copy

a = [1, 2, 3, 4, 5]
b = copy.deepcopy(a)
print("a = ", a)
print("b = ", b)
print(" ")

a[0] = 100
print("a = ", a)
print("b = ", b)

a =  [1, 2, 3, 4, 5]
b =  [1, 2, 3, 4, 5]
 
a =  [100, 2, 3, 4, 5]
b =  [1, 2, 3, 4, 5]


## Operations on lists

1. Study and discuss the code.
2. What does + do?
3. Use + to generate 5 copies of a list.
4. What dows * do?
5. Use * to generate 10 copies of an element.



In [ ]:
# Length of list
a = [1, 2, 3]
print("len(a) = ", len(a))

# Concatenation using +
a = [1, 2]
b = [3, 4, 5]
c = a + b
print("c = ", c)


# Multiplication: * = duplicate.
a = [2]
b = a*3
print("b = ", b)

## A list of lists

1. Study the code below and discuss.
2. What does * do?
3. What does + do?
4. Create a list of 10 lists of [1, 2] using *


In [ ]:
# A simple list
a = [1,  2, 3]
print("a = ", a)

# Create a list of lists directly:
b = [[1, 2, 3], [4, 5, 6]]
print("b = ", b)
print("len(b) = ", len(b))
print(" ")

# The * operator on a simple list
c = b*2
print( "c = ", c)

# The + operator
d = b + b
print("d = ", d)

a =  [1, 2, 3]
b =  [[1, 2, 3], [4, 5, 6]]
len(b) =  2
 
c =  [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
d =  [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


## Indexing lists

1. Study the example.
2. What does indexing the row a[i] for i>=0 do?
3. What does indexing the row a[i] for i<0 do?
4. Discuss how element indexing works.
5. What does a[-2][-1] represent? Verify your answer.


In [ ]:
# Create a list:
a = [[1, 2, 3], [4, 5, 6]] # Two 1D lists make a list of lists.

# Access by rows:
print("a[0] = ", a[0])   # First element.
print("a[1] = ", a[1])   # Second element.
print("a[-1] = ", a[-1]) # Last element.
print("a[-2] = ", a[-2]) # Second to last element.
print(" ")

# Access by elements:
print("a[0][0] = ", a[0][0]) # First row. First element.
print("a[0][1] = ", a[0][1]) # First row. Second elment.
print("a[0][2] = ", a[0][2]) # First row. Third element.
print("a[1][0] = ", a[1][0]) # Fill in!
print(" ")

# Some negative indices:
print("a[-1][-2] = ", a[-1][-2]) # Explain the output.

a[0] =  [1, 2, 3]
a[1] =  [4, 5, 6]
a[-1] =  [4, 5, 6]
a[-2] =  [1, 2, 3]
 
a[0][0] =  1
a[0][1] =  2
a[0][2] =  3
a[1][0] =  4
a[-1][-2] =  5


## Accessing elements using for loops and "in"

1. Study and discuss the example.
2. Modify the example for b = [3, 2, 1]. What do you observe about the order that you are retrieving the elements?

In [ ]:
row_array = [1, 2, 3]
print(row_array)

# Access elements using for-loop and in:
for a in row_array:
  print(a)


[1, 2, 3]
1
2
3


## Accessing elements in a list of lists using two for loops and "in"

1. Study the example and discuss within your group.
2. Modify the example for [[0, 1, 2], [3, 4]]. What do you observe?

In [ ]:
array_2d = [[1, 2, 3], [4, 5, 6]]
print(array_2d)

# Access elements using for-loop and in:
for row in array_2d: # Retrieve a row.
  for a in row:      # Retrieve an elements within the row.
    print(a)

## Acessing element index using enum

1. Note that the indices are the same as for the image generation WebApp.
2. What is the row and column for 5? Explain.
3. What is the row and column for 3? Explain.

In [ ]:
array_2d = [[1, 2, 3], [4, 5, 6]]
print(array_2d)

# Access elements using for-loop and in:
for i, row in enumerate(array_2d): # Retrieve a row.
  print("row i = ", i, " row = ", row)
  for j, a in enumerate(row):      # Retrieve an elements within the row.
    print("Column j = ", j, " element = ", a)


[[1, 2, 3], [4, 5, 6]]
row i =  0  row =  [1, 2, 3]
Column j =  0  element =  1
Column j =  1  element =  2
Column j =  2  element =  3
row i =  1  row =  [4, 5, 6]
Column j =  0  element =  4
Column j =  1  element =  5
Column j =  2  element =  6


## Combining two arrays of different types using zip

1. Study the code and discuss.
2. Add "Antonia" with an age of 20 and verify.

In [ ]:
names = ["Marios", "Sylvia", "Rebecca"] # Array of 3 strings.
ages  = [57, 56, 25] # Array of 3 values

for name, age in zip(names, ages): # zip retrieves values with the same index.
  print(name, age)

Marios 57
Sylvia 56
Rebecca 25


## Slices within a list (stride=1)

1. Study the code.

In [ ]:
# Create a list:
a = [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]
print("a = ", a)
print(" ")

# Use : to access elements inside a column
# This does not work.
print("a[:] = ", a[:])
print("a[0][1:4] = ", a[0][1:4])
print("a[1][0:3] = ", a[1][0:3])

a =  [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]
 
a[:] =  [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]
a[0][1:4] =  [2, 3, 4]
a[1][0:3] =  [7, 8, 9]


## Slices using a different stride (stride=2)



In [ ]:
# Create a list:
a = [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]
print("a = ", a)
print(" ")

# Use : to access elements inside a column
# This does not work.
print("a[0][1:4:2] = ", a[0][1:4:2])   # access every 2 elements.
print("a[1][1:7:2] = ", (a[1])[1:7:2]) # access every 2 elements.

a =  [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]
 
a[0][1:4:2] =  [2, 4]
a[1][1:7:2] =  [8, 10, 12]


## Cannot access columns in regular lists

Note that the first index refers to the elements in the list (rows).
1. Study the code and discuss. What is surprising here?
2. Why does the code work this way?

In [ ]:
# Create a list:
a = [[1, 2, 3], [4, 5, 6]]
print("a = ", a)
print(" ")

# Use : to access elements inside a column
# This does not work.
print("a[:] = ", a[:])
print("a[:][0] = ", a[:][0]) # What happened here?
print("a[0:2][0] = ", a[0:2][0])


a =  [[1, 2, 3], [4, 5, 6]]
 
a[:] =  [[1, 2, 3], [4, 5, 6]]
a[:][0] =  [1, 2, 3]
a[0:2][0] =  [1, 2, 3]


# NumPy arrays

## Create arrays using np.array()

NumPy array allow us to use fast arithmetic for list of lists or 2D matrices.

This is a new type of variable. Note that type refers to the kind of data that we can store.

We require an equal number of elements in each component list.

Assignment:
1. Note that np.array() is just used for converting to a new type.
2. What do you understand by a new type?  
3. Study the code and comment on why the last example fails.

In [ ]:
import numpy as np # import all the functions from numpy library. Use np for its functions.

str = "A string example"
print("str has type = ", type(str)) # type is used to return the kind of data.

num = 5.12
print("num has type = ", type(num))  # type returns the kind of data.

a = [[1, 2, 3], [4, 5, 6]] # regular list.
print(type(a))             # print the type of variable that a "is"

a_np = np.array(a)         # create numpy array.
print(a_np, type(a_np))    # We have a new type.

b = [[1, 2, 3], [4, 5]]    # b has lists of different sizes.
b_np = np.array(b)         # Conversion is not possible!
print(b_np)


str has type =  <class 'str'>
num has type =  <class 'float'>
<class 'list'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

1. Study the code.
2. Explain the values for len(b) and b.shape.

In [ ]:
import numpy as np

# Create a list:
a = [[1, 2, 3], [4, 5, 6]]

# Create a 2D NumPy array
b = np.array(a)

print("a = ", a, ", len(a) = ", len(a), ", type(a) = ", type(a))
print("b = ", b)
print("len(b) = ", len(b), ", b.shape = ", b.shape, ", type(b) = ", type(b))
print(" ")

a =  [[1, 2, 3], [4, 5, 6]] , len(a) =  2 type(a) =  <class 'list'>
b =  [[1 2 3]
 [4 5 6]]
len(b) =  2 , b.shape =  (2, 3) type(b) =  <class 'numpy.ndarray'>
 


## 1D matrix array creation using *

1. Study the code.
2. Create a 5 element row with the element of 6.

In [ ]:
print("List comprehension for a row")
c = np.array([3*[1]])
print("c = ", c)
print("len(c) = ", len(c), ", b.shape = ", c.shape)
print(" ")


## 2D matrix array creation using a list comprehension

1. Study the code below.
2. Explain the value of len(d).
3. Explain the value of d.shape.
4. Modify the example to make the shape (3, 5) of 2.

In [ ]:
d = np.array([3*[1] for row in range(4)])
print("d = ", d)
print("len(d) = ", len(d), ", d.shape = ", d.shape)
print(" ")

d =  [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
len(d) =  4 , d.shape =  (4, 3)
 


## Accessing NumPy Array elements

1. Study the code carefully.
2. Explain how b[0][0:2] prints what you get.


In [ ]:
# Create a list:
a = [[1, 2, 3], [4, 5, 6]]

# Create a 2D NumPy array
b = np.array(a)
print("b=", b)
print(" ")

print("Like lists: Access row by row.")
print("b[0] = ", b[0])
print("b[1] = ", b[1])
print(" ")

print("Like lists: Access elements using 2d indices")
print("b[0][0] = ", b[0][0])
print("b[1][2] = ", b[1][2])
print(" ")

print("Like lists: Access using 1D strides")
print("b[0][1:3] = ", b[0][1:3])
print("b[1][0:2] = ", b[1][0:2])
print("b[1][0:3:2] = ", b[1][0:3:2])
print(" ")

b= [[1 2 3]
 [4 5 6]]
 
Like lists: Access row by row.
b[0] =  [1 2 3]
b[1] =  [4 5 6]
 
Like lists: Access elements using 2d indices
b[0][0] =  1
b[1][2] =  6
 
Like lists: Access using strides
b[0][1:3] =  [2 3]
b[1][0:2] =  [4 5]
b[1][0:3:2] =  [4 6]
 


## Accessing 2D blocks

1. Study the code below.
2. Changing the single element 10 to 3.
3. Change the top row to all 1. Verify your answer.
4. Change the first column to 10. Verify your answer.
5. Change the lower-right elements to 5, 6. Verify your answer.

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("1. a = ", a)

print("2. a[0, 0] = ", a[0,0])
print("3. a[1, 0] = ", a[1,0])

a[1, 0] = 10
print("4. a[1, 0] = ", a[1,0])

a[0:2, 3:] = 5
print("5. a = ", a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
a[]= 1
a[]= 6
a =  [[ 1  2  3 -1 -1]
 [ 6  7  8 -1 -1]]


## Note "=" in Python does not copy NumPy array elements.

1. Study what happens after a[0]=100.
2. Explain what is unexpected here and why.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = a
print("a = ", a)
print("b = ", b)
print(" ")

a[0] = 100
print("a = ", a)
print("b = ", b)

a =  [1 2 3 4 5]
b =  [1 2 3 4 5]
 
a =  [100   2   3   4   5]
b =  [100   2   3   4   5]


## Copying NumPy arrays

1. What line did we change here?
2. How is the output different?

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = a.copy()
print("a = ", a)
print("b = ", b)
print(" ")

a[0] = 100
print("a = ", a)
print("b = ", b)

a =  [1 2 3 4 5]
b =  [1 2 3 4 5]
 
a =  [100   2   3   4   5]
b =  [1 2 3 4 5]


## Flattening arrays to one dimension

1. Study the code and discuss.
2. How is the size of b related to a?
3. How is b related to a?
4. Modify a to [[1, 2], [3, 4], [5, 6], [7, 8]]. What happens to b? Why?

In [ ]:
import numpy as np

a = np.array([[1, 2], [1, 2], [4, 5]]) # create an array.
b = a.flatten() # flatten all dimensions.

print("a = ", a, ", a.shape = ", a.shape)
print("b = ", b, ", b.shape = ", b.shape)


a =  [[1 2]
 [1 2]
 [4 5]] , a.shape =  (3, 2)
b =  [1 2 1 2 4 5] , b.shape =  (6,)


## Reshaping array rows into 2D matrices (e.g., images)

1. Study the code carefully.
2. Can you reshape each element to a size of 4x1. Why?
3. Can you reshape each element to a size of 3x2. Why or why not? Explain.

In [ ]:
# Original matrix has a square number of elements in each row.
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("a = ", a, ", a.shape = ", a.shape)
print(" ")

# Reshape each row:
for element in a:
  b = element.reshape(2, 2) # Reshape into 2 by 2.
  print("b = ", b, ", b.shape = ", b.shape)


a =  [[1 2 3 4]
 [5 6 7 8]] , a.shape =  (2, 4)
 
b =  [[1 2]
 [3 4]] , b.shape =  (2, 2)
b =  [[5 6]
 [7 8]] , b.shape =  (2, 2)


## A video as list of numpy frames.

1. Study the example carefully.
2. Add frame5 with some values. Verify your answer.
3. Comment out frame1 and frame2. Does it work? Explain.

In [ ]:
# Individual frames
frame1 = np.array([1, 2])
frame2 = np.array([3, 4])
frame3 = np.array([5, 6])
frame4 = np.array([7, 8])

video = [frame1, frame2, frame3, frame4]
print("video = ", video, ", type(video) = ")
print(" ")

for frame in video:
  print("frame = ", frame)

video =  [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])] , type(video) =  <class 'list'>
 
frame =  [1 2]
frame =  [3 4]
frame =  [5 6]
frame =  [7 8]
